### ISSUE TITLE
_pickle.UnpicklingError: the STRING opcode argument must be quoted

### ISSUE THREAD

**Issue by salmaShahid** [danbochman/Real-Time-Action-Recognition#4]
Hey while running the following command
python spatial_cnn_cpu.py --resume model_best.pth.tar --demo

I got this pickle error
File "spatial_cnn_cpu.py", line 38, in main
    train_loader, test_loader, test_video = data_loader.run()
  File "C:\Users\LeNoVo T430\Desktop\Real-Time-Action-Recognition\dataloader\spatial_dataloader.py", line 96, in run
    self.load_frame_count()
  File "C:\Users\LeNoVo T430\Desktop\Real-Time-Action-Recognition\dataloader\spatial_dataloader.py", line 85, in load_frame_count
    dic_frame = pickle.load(file)

_pickle.UnpicklingError: the STRING opcode argument must be quoted

plz guide me how can i solve this problem

**Comment by danbochman** [comment]
Hey,

It seems like a compatibility / version problem, and not a problem with the code itself.
In an e-mail you've sent me you mentioned that you're using Python 3.6.8
This repository was written on Python 2.7, so maybe try that?

**Comment by salmaShahid** [comment]
thank you so much sir for your reply!
Sir can you please guide me any alternative solution of this  issue...!
